Implement Mutex Hat Prediction
jmesyou/gvisor pull request #2
Opened 2021-10-29 16:05 UTC by jmesyou

This CL implements mutex hat prediction for lock annotations
on `struct` types. The prediction logic is currently limited
to structs where a field follows a mutex with only other
fields or doc lines in between, with no line breaks.

For example:

```Go
type Foo struct {
    mu            Mutex // mutex hat start
    guardedField1 int
    // Doc
    guardedField2 int   // mutex hat end

    unguardedField int
}
```

2021-10-29 18:28 UTC, zpavlinovic commented on tools/checklocks/facts.go
> +							lgf.Inferred = make(map[string]bool)
Could we initialize this after introducing lgf?

2021-10-29 18:30 UTC, zpavlinovic commented on tools/checklocks/facts.go
> +		if typeName := fieldObj.Type().String(); isMutexType(typeName) {
We can probably do away with typeName here and inline in the call to isMutexType.

2021-10-29 18:34 UTC, zpavlinovic commented on tools/checklocks/facts.go
> +
nit: delete this line

2021-10-29 18:36 UTC, zpavlinovic commented on tools/checklocks/test/test.go
> +
We could probably add examples with mixed fixed annotations and inferred ones?

2021-10-31 20:02 UTC, timothy-king requested changes

2021-10-31 20:02 UTC, timothy-king commented on tools/checklocks/facts.go
> +	Inferred map[string]bool
Whatever you pick, make sure to propagate name changes to related methods and functions.

2021-11-01 20:34 UTC, jmesyou commented on tools/checklocks/facts.go
> +		guardName := mutexHatOf[i]
AFAICT, This was a mistake, it should be `mutexHatOf[line]`!

2021-11-01 21:12 UTC, timothy-king approved these changes

2021-11-02 15:35 UTC, merged